### ISSUE TITLE
More responsive design

### ISSUE THREAD

**Issue by ghost** [ashleemboyer/textua11y#1]
Current design is not responsive. For example, it breaks on devices with small screen width (like phones in portrait mode), borders become wrong-sized with certain heights, and, for features like palettes, where the sidebar needs to scroll, everything scrolls instead, which can be quite annoying.

So, I've made a little To-Do list:
- [ ] Make a more flexible layout (current layout just doesn't move, and sidebar's width doesn't change when I resize the browser)
- [ ] Hide the sidebar when the width is smaller than certain value (can be achieved with media queries, but I don't know what value (probably can be achievable using JavaScript and HTMLs `<details>` tag too))
- [ ] Make the `#sidebar` scroll independently from the `#content`
- [ ] Make the color pickers collapsible (is achievable using HTML's `<details>` tag)

**Comment by mishaor** [comment]
this is so sad alexa play despacito
